$ErrorActionPreference = 'Stop'

try {
    $root = Split-Path -Parent $MyInvocation.MyCommand.Path
    $mediaRoot = Join-Path $root 'media'
    $indexPath = Join-Path $root 'media_index.js'

    $types = @('photos','videos','nature','wildlife')
    $result = [ordered]@{}

    foreach ($type in $types) {
        $typePath = Join-Path $mediaRoot $type
        $folders = @()

        if (Test-Path -LiteralPath $typePath) {
            Get-ChildItem -LiteralPath $typePath -Directory | Sort-Object Name | ForEach-Object {
                $folder = $_
                $files = @(
                    Get-ChildItem -LiteralPath $folder.FullName -File |
                    Sort-Object Name |
                    ForEach-Object { $_.Name }
                )

                $folders += [pscustomobject]@{
                    name  = $folder.Name
                    files = $files
                }
            }
        }

        $result[$type] = $folders
    }

    $json = $result | ConvertTo-Json -Depth 10 -Compress
    $content = @"
// Auto-generated by UPDATE_MEDIA_INDEX.bat.
// Safe to regenerate after adding, deleting or replacing media.
window.TRJ_CONFIG = window.TRJ_CONFIG || {};
window.TRJ_CONFIG.folders = $json;
"@

    Set-Content -LiteralPath $indexPath -Value $content -Encoding UTF8

    Write-Host ''
    Write-Host 'MEDIA INDEX UPDATED SUCCESSFULLY' -ForegroundColor Green
    Write-Host 'Add/delete/replace files any time, then run this updater again.' -ForegroundColor Cyan
    Write-Host 'Now refresh index.html with Ctrl + R.' -ForegroundColor Yellow
    Write-Host ''
}
catch {
    Write-Host ''
    Write-Host 'MEDIA UPDATE FAILED' -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Yellow
    Write-Host ''
    Write-Host 'The window will stay open so you can read the error.' -ForegroundColor Gray
    Write-Host ''
}

Read-Host 'Press ENTER to close'
